# IF3070 Foundations of Artificial Intelligence | Tugas Besar 2

This notebook serves as a template for the assignment. Please create a copy of this notebook to complete your work. You can add more code blocks, markdown blocks, or new sections if needed.

Group Number: xx

Group Members:
- Name (NIM)
- Name (NIM)
- ...

## Import Libraries

In [667]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

# Import other libraries if needed

## Import Dataset

In [669]:
# Example of reading a csv file from a gdrive link

# Take the file id from the gdrive file url
# https://drive.google.com/file/d/1ZUtiaty9RPXhpz5F2Sy3dFPHF4YIt5iU/view?usp=sharing => The file id is 1ZUtiaty9RPXhpz5F2Sy3dFPHF4YIt5iU
# and then put it in this format:
# https://drive.google.com/uc?id={file_id}
# Don't forget to change the access to public

df = pd.read_csv("train.csv")
print(df.shape)
df.head()

(140404, 56)

,id,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,1,NaN,https://www.northcm.ac.th,24.0,www.northcm.ac.th,17.0,0.0,NaN,0.800000,NaN,...,0.0,0.0,1.0,NaN,3.0,NaN,69.0,NaN,NaN,1
1,4,8135291.txt,http://uqr.to/1il1z,NaN,NaN,NaN,NaN,to,1.000000,0.000896,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,0
2,5,586561.txt,https://www.woolworthsrewards.com.au,35.0,www.woolworthsrewards.com.au,28.0,0.0,au,0.857143,NaN,...,1.0,0.0,1.0,33.0,7.0,8.0,15.0,NaN,2.0,1
3,6,NaN,NaN,31.0,NaN,NaN,NaN,com,0.562500,0.522907,...,1.0,0.0,1.0,24.0,5.0,14.0,NaN,NaN,NaN,1
4,11,412632.txt,NaN,NaN,www.nyprowrestling.com,22.0,0.0,NaN,1.000000,NaN,...,0.0,0.0,1.0,NaN,NaN,14.0,NaN,0.0,NaN,1

In [670]:

# Create new DataFrame with only URL and label columns
df_test = df[['URL', 'label']]

# Drop rows where URL is NaN
df_test = df_test.dropna(subset=['URL'])

# Calculate and display statistics
print("\nTotal rows before dropping NaN URLs:", len(df))
print("Total rows after dropping NaN URLs:", len(df_test))
print("Rows removed:", len(df) - len(df_test))

# Calculate and display label proportions
label_counts = df_test['label'].value_counts()
label_proportions = df_test['label'].value_counts(normalize=True) * 100

print("\nLabel Counts:")
print(label_counts)
print("\nLabel Proportions (%):")
print(label_proportions)

Total rows before dropping NaN URLs: 140404
Total rows after dropping NaN URLs: 96917
Rows removed: 43487

Label Counts:
label
1    89672
0     7245
Name: count, dtype: int64

Label Proportions (%):
label
1    92.524531
0     7.475469
Name: proportion, dtype: float64

# 1. Split Training Set and Validation Set

Splitting the training and validation set works as an early diagnostic towards the performance of the model we train. This is done before the preprocessing steps to **avoid data leakage inbetween the sets**. If you want to use k-fold cross-validation, split the data later and do the cleaning and preprocessing separately for each split.

Note: For training, you should use the data contained in the `train` folder given by the TA. The `test` data is only used for kaggle submission.

In [672]:
# Split training set and validation set here, store into variables train_set and val_set.
# Remember to also keep the original training set before splitting. This will come important later.
# train_set, val_set = ...

import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, StratifiedKFold

def prepare_kfold_split(df, n_splits=100, shuffle=True, random_state=50, stratify=True):
    """
    Prepare k-fold cross validation splits of the data.
    
    Parameters:
    -----------
    df : pandas DataFrame
        The input dataset
    n_splits : int, default=5
        Number of folds
    shuffle : bool, default=True
        Whether to shuffle the data before splitting
    random_state : int, default=50
        Random seed for reproducibility
    stratify : bool, default=True
        Whether to use stratified k-fold to maintain label distribution
        
    Returns:
    --------
    list of tuples
        Each tuple contains (train_indices, val_indices) for each fold
    """
    
    # Make a copy of the dataframe
    df = df.copy()
    
    # Choose the appropriate KFold class
    if stratify:
        kf = StratifiedKFold(n_splits=n_splits, shuffle=shuffle, random_state=random_state)
        splits = kf.split(df, df['label'])
    else:
        kf = KFold(n_splits=n_splits, shuffle=shuffle, random_state=random_state)
        splits = kf.split(df)
    
    # Store the fold information
    fold_indices = []
    
    # Generate and store the indices for each fold
    for i, (train_idx, val_idx) in enumerate(splits):
        fold_indices.append((train_idx, val_idx))
        
        # Print information about this fold
        print(f"\nFold {i+1}:")
        print(f"Training samples: {len(train_idx)}")
        print(f"Validation samples: {len(val_idx)}")
        
        # Print label distribution for this fold
        train_labels = df.iloc[train_idx]['label'].value_counts(normalize=True).round(3)
        val_labels = df.iloc[val_idx]['label'].value_counts(normalize=True).round(3)
        
        print("\nTraining label distribution:")
        print(train_labels)
        print("\nValidation label distribution:")
        print(val_labels)
    
    return fold_indices

def get_fold_data(df, fold_indices, fold_number):
    """
    Get the training and validation data for a specific fold.
    
    Parameters:
    -----------
    df : pandas DataFrame
        The input dataset
    fold_indices : list of tuples
        The fold indices returned by prepare_kfold_split
    fold_number : int
        The fold number to get (1-based indexing)
        
    Returns:
    --------
    train_df, val_df : tuple of pandas DataFrames
        The training and validation data for the specified fold
    """
    if fold_number < 1 or fold_number > len(fold_indices):
        raise ValueError(f"Fold number must be between 1 and {len(fold_indices)}")
    
    # Get the indices for the specified fold
    train_idx, val_idx = fold_indices[fold_number - 1]
    
    # Create the training and validation sets
    train_df = df.iloc[train_idx].reset_index(drop=True)
    val_df = df.iloc[val_idx].reset_index(drop=True)
    
    return train_df, val_df

# Example usage:
# fold_indices = prepare_kfold_split(df)
# For working with a specific fold (e.g., fold 1):
# train_df, val_df = get_fold_data(df, fold_indices, fold_number=1)

In [673]:
train_set, val_set = prepare_data_split(df)

train_set.head()

Total samples: 140404
Training samples: 112323 (80.0%)
Validation samples: 28081 (20.0%)

Label distribution:

Training set:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation set:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

,id,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,105237,804816.txt,NaN,19.0,NaN,12.0,0.0,NaN,1.0,NaN,...,NaN,NaN,1.0,21.0,NaN,25.0,93.0,3.0,22.0,1
1,116818,824661.txt,NaN,NaN,NaN,27.0,0.0,uk,0.9,0.028555,...,NaN,NaN,0.0,0.0,NaN,13.0,19.0,0.0,15.0,1
2,83242,123833.txt,NaN,19.0,NaN,NaN,NaN,NaN,1.0,0.012927,...,NaN,NaN,NaN,15.0,14.0,25.0,NaN,2.0,NaN,1
3,223555,NaN,https://www.carbodydesign.com,NaN,www.carbodydesign.com,21.0,0.0,com,1.0,0.522907,...,0.0,0.0,1.0,48.0,12.0,9.0,328.0,2.0,127.0,1
4,92248,NaN,NaN,24.0,www.cycling.or.kr,NaN,NaN,NaN,0.8,0.002273,...,NaN,0.0,NaN,NaN,4.0,NaN,103.0,NaN,NaN,1

In [674]:
x = df.drop('label', axis=1)
y = df['label']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 4)

In [675]:
val_set.head()

,id,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,73245,786761.txt,https://www.projectgentsintpieters.be,36.0,www.projectgentsintpieters.be,29.0,0.0,NaN,1.0000,NaN,...,NaN,NaN,1.0,17.0,NaN,4.0,133.0,NaN,141.0,1
1,230854,NaN,NaN,31.0,NaN,NaN,0.0,com,0.5625,NaN,...,0.0,NaN,1.0,NaN,3.0,NaN,35.0,0.0,31.0,1
2,93009,NaN,NaN,NaN,NaN,12.0,0.0,org,NaN,NaN,...,NaN,0.0,1.0,NaN,NaN,NaN,154.0,0.0,NaN,1
3,15162,NaN,https://www.soratemplates.com,28.0,www.soratemplates.com,NaN,0.0,com,1.0000,NaN,...,1.0,0.0,NaN,53.0,NaN,9.0,135.0,1.0,141.0,1
4,83435,NaN,NaN,26.0,NaN,NaN,0.0,com,1.0000,NaN,...,0.0,0.0,1.0,NaN,3.0,12.0,65.0,0.0,NaN,1

# 2. Data Cleaning and Preprocessing

This step is the first thing to be done once a Data Scientist have grasped a general knowledge of the data. Raw data is **seldom ready for training**, therefore steps need to be taken to clean and format the data for the Machine Learning model to interpret.

By performing data cleaning and preprocessing, you ensure that your dataset is ready for model training, leading to more accurate and reliable machine learning results. These steps are essential for transforming raw data into a format that machine learning algorithms can effectively learn from and make predictions.

We will give some common methods for you to try, but you only have to **at least implement one method for each process**. For each step that you will do, **please explain the reason why did you do that process. Write it in a markdown cell under the code cell you wrote.**

## A. Data Cleaning

**Data cleaning** is the crucial first step in preparing your dataset for machine learning. Raw data collected from various sources is often messy and may contain errors, missing values, and inconsistencies. Data cleaning involves the following steps:

1. **Handling Missing Data:** Identify and address missing values in the dataset. This can include imputing missing values, removing rows or columns with excessive missing data, or using more advanced techniques like interpolation.

2. **Dealing with Outliers:** Identify and handle outliers, which are data points significantly different from the rest of the dataset. Outliers can be removed or transformed to improve model performance.

3. **Data Validation:** Check for data integrity and consistency. Ensure that data types are correct, categorical variables have consistent labels, and numerical values fall within expected ranges.

4. **Removing Duplicates:** Identify and remove duplicate rows, as they can skew the model's training process and evaluation metrics.

5. **Feature Engineering**: Create new features or modify existing ones to extract relevant information. This step can involve scaling, normalizing, or encoding features for better model interpretability.

### I. Handling Missing Data

Missing data can adversely affect the performance and accuracy of machine learning models. There are several strategies to handle missing data in machine learning:

1. **Data Imputation:**

    a. **Mean, Median, or Mode Imputation:** For numerical features, you can replace missing values with the mean, median, or mode of the non-missing values in the same feature. This method is simple and often effective when data is missing at random.

    b. **Constant Value Imputation:** You can replace missing values with a predefined constant value (e.g., 0) if it makes sense for your dataset and problem.

    c. **Imputation Using Predictive Models:** More advanced techniques involve using predictive models to estimate missing values. For example, you can train a regression model to predict missing numerical values or a classification model to predict missing categorical values.

2. **Deletion of Missing Data:**

    a. **Listwise Deletion:** In cases where the amount of missing data is relatively small, you can simply remove rows with missing values from your dataset. However, this approach can lead to a loss of valuable information.

    b. **Column (Feature) Deletion:** If a feature has a large number of missing values and is not critical for your analysis, you can consider removing that feature altogether.

3. **Domain-Specific Strategies:**

    a. **Domain Knowledge:** In some cases, domain knowledge can guide the imputation process. For example, if you know that missing values are related to a specific condition, you can impute them accordingly.

4. **Imputation Libraries:**

    a. **Scikit-Learn:** Scikit-Learn provides a `SimpleImputer` class that can handle basic imputation strategies like mean, median, and mode imputation.

    b. **Fancyimpute:** Fancyimpute is a Python library that offers more advanced imputation techniques, including matrix factorization, k-nearest neighbors, and deep learning-based methods.

The choice of imputation method should be guided by the nature of your data, the amount of missing data, the problem you are trying to solve, and the assumptions you are willing to make.

In [679]:
# Write your code here

### II. Dealing with Outliers

Outliers are data points that significantly differ from the majority of the data. They can be unusually high or low values that do not fit the pattern of the rest of the dataset. Outliers can significantly impact model performance, so it is important to handle them properly.

Some methods to handle outliers:
1. **Imputation**: Replace with mean, median, or a boundary value.
2. **Clipping**: Cap values to upper and lower limits.
3. **Transformation**: Use log, square root, or power transformations to reduce their influence.
4. **Model-Based**: Use algorithms robust to outliers (e.g., tree-based models, Huber regression).

In [681]:
# Write your code here

### III. Remove Duplicates
Handling duplicate values is crucial because they can compromise data integrity, leading to inaccurate analysis and insights. Duplicate entries can bias machine learning models, causing overfitting and reducing their ability to generalize to new data. They also inflate the dataset size unnecessarily, increasing computational costs and processing times. Additionally, duplicates can distort statistical measures and lead to inconsistencies, ultimately affecting the reliability of data-driven decisions and reporting. Ensuring data quality by removing duplicates is essential for accurate, efficient, and consistent analysis.

In [683]:
# Write your code here

### IV. Feature Engineering

**Feature engineering** involves creating new features (input variables) or transforming existing ones to improve the performance of machine learning models. Feature engineering aims to enhance the model's ability to learn patterns and make accurate predictions from the data. It's often said that "good features make good models."

1. **Feature Selection:** Feature engineering can involve selecting the most relevant and informative features from the dataset. Removing irrelevant or redundant features not only simplifies the model but also reduces the risk of overfitting.

2. **Creating New Features:** Sometimes, the existing features may not capture the underlying patterns effectively. In such cases, engineers create new features that provide additional information. For example:
   
   - **Polynomial Features:** Engineers may create new features by taking the square, cube, or other higher-order terms of existing numerical features. This can help capture nonlinear relationships.
   
   - **Interaction Features:** Interaction features are created by combining two or more existing features. For example, if you have features "length" and "width," you can create an "area" feature by multiplying them.

3. **Binning or Discretization:** Continuous numerical features can be divided into bins or categories. For instance, age values can be grouped into bins like "child," "adult," and "senior."

4. **Domain-Specific Feature Engineering:** Depending on the domain and problem, engineers may create domain-specific features. For example, in fraud detection, features related to transaction history and user behavior may be engineered to identify anomalies.

Feature engineering is both a creative and iterative process. It requires a deep understanding of the data, domain knowledge, and experimentation to determine which features will enhance the model's predictive power.

In [685]:
# Write your code here

## B. Data Preprocessing

**Data preprocessing** is a broader step that encompasses both data cleaning and additional transformations to make the data suitable for machine learning algorithms. Its primary goals are:

1. **Feature Scaling:** Ensure that numerical features have similar scales. Common techniques include Min-Max scaling (scaling to a specific range) or standardization (mean-centered, unit variance).

2. **Encoding Categorical Variables:** Machine learning models typically work with numerical data, so categorical variables need to be encoded. This can be done using one-hot encoding, label encoding, or more advanced methods like target encoding.

3. **Handling Imbalanced Classes:** If dealing with imbalanced classes in a binary classification task, apply techniques such as oversampling, undersampling, or using different evaluation metrics to address class imbalance.

4. **Dimensionality Reduction:** Reduce the number of features using techniques like Principal Component Analysis (PCA) or feature selection to simplify the model and potentially improve its performance.

5. **Normalization:** Normalize data to achieve a standard distribution. This is particularly important for algorithms that assume normally distributed data.

### Notes on Preprocessing processes

It is advised to create functions or classes that have the same/similar type of inputs and outputs, so you can add, remove, or swap the order of the processes easily. You can implement the functions or classes by yourself

or

use `sklearn` library. To create a new preprocessing component in `sklearn`, implement a corresponding class that includes:
1. Inheritance to `BaseEstimator` and `TransformerMixin`
2. The method `fit`
3. The method `transform`

In [688]:
# Example

# from sklearn.base import BaseEstimator, TransformerMixin

# class FeatureEncoder(BaseEstimator, TransformerMixin):

#     def fit(self, X, y=None):

#         # Fit the encoder here

#         return self

#     def transform(self, X):
#         X_encoded = X.copy()

#         # Encode the categorical variables here

#         return X_encoded

### I. Feature Scaling

**Feature scaling** is a preprocessing technique used in machine learning to standardize the range of independent variables or features of data. The primary goal of feature scaling is to ensure that all features contribute equally to the training process and that machine learning algorithms can work effectively with the data.

Here are the main reasons why feature scaling is important:

1. **Algorithm Sensitivity:** Many machine learning algorithms are sensitive to the scale of input features. If the scales of features are significantly different, some algorithms may perform poorly or take much longer to converge.

2. **Distance-Based Algorithms:** Algorithms that rely on distances or similarities between data points, such as k-nearest neighbors (KNN) and support vector machines (SVM), can be influenced by feature scales. Features with larger scales may dominate the distance calculations.

3. **Regularization:** Regularization techniques, like L1 (Lasso) and L2 (Ridge) regularization, add penalty terms based on feature coefficients. Scaling ensures that all features are treated equally in the regularization process.

Common methods for feature scaling include:

1. **Min-Max Scaling (Normalization):** This method scales features to a specific range, typically [0, 1]. It's done using the following formula:

   $$X' = \frac{X - X_{min}}{X_{max} - X_{min}}$$

   - Here, $X$ is the original feature value, $X_{min}$ is the minimum value of the feature, and $X_{max}$ is the maximum value of the feature.  
<br />
<br />
2. **Standardization (Z-score Scaling):** This method scales features to have a mean (average) of 0 and a standard deviation of 1. It's done using the following formula:

   $$X' = \frac{X - \mu}{\sigma}$$

   - $X$ is the original feature value, $\mu$ is the mean of the feature, and $\sigma$ is the standard deviation of the feature.  
<br />
<br />
3. **Robust Scaling:** Robust scaling is a method that scales features to the interquartile range (IQR) and is less affected by outliers. It's calculated as:

   $$X' = \frac{X - Q1}{Q3 - Q1}$$

   - $X$ is the original feature value, $Q1$ is the first quartile (25th percentile), and $Q3$ is the third quartile (75th percentile) of the feature.  
<br />
<br />
4. **Log Transformation:** In cases where data is highly skewed or has a heavy-tailed distribution, taking the logarithm of the feature values can help stabilize the variance and improve scaling.

The choice of scaling method depends on the characteristics of your data and the requirements of your machine learning algorithm. **Min-max scaling and standardization are the most commonly used techniques and work well for many datasets.**

Scaling should be applied separately to each training and test set to prevent data leakage from the test set into the training set. Additionally, **some algorithms may not require feature scaling, particularly tree-based models.**

In [690]:
# Write your code here

### II. Feature Encoding

**Feature encoding**, also known as **categorical encoding**, is the process of converting categorical data (non-numeric data) into a numerical format so that it can be used as input for machine learning algorithms. Most machine learning models require numerical data for training and prediction, so feature encoding is a critical step in data preprocessing.

Categorical data can take various forms, including:

1. **Nominal Data:** Categories with no intrinsic order, like colors or country names.  

2. **Ordinal Data:** Categories with a meaningful order but not necessarily equidistant, like education levels (e.g., "high school," "bachelor's," "master's").

There are several common methods for encoding categorical data:

1. **Label Encoding:**

   - Label encoding assigns a unique integer to each category in a feature.
   - It's suitable for ordinal data where there's a clear order among categories.
   - For example, if you have an "education" feature with values "high school," "bachelor's," and "master's," you can encode them as 0, 1, and 2, respectively.
<br />
<br />
2. **One-Hot Encoding:**

   - One-hot encoding creates a binary (0 or 1) column for each category in a nominal feature.
   - It's suitable for nominal data where there's no inherent order among categories.
   - Each category becomes a new feature, and the presence (1) or absence (0) of a category is indicated for each row.
<br />
<br />
3. **Target Encoding (Mean Encoding):**

   - Target encoding replaces each category with the mean of the target variable for that category.
   - It's often used for classification problems.

In [692]:
# Write your code here

### III. Handling Imbalanced Dataset

**Handling imbalanced datasets** is important because imbalanced data can lead to several issues that negatively impact the performance and reliability of machine learning models. Here are some key reasons:

1. **Biased Model Performance**:

 - Models trained on imbalanced data tend to be biased towards the majority class, leading to poor performance on the minority class. This can result in misleading accuracy metrics.

2. **Misleading Accuracy**:

 - High overall accuracy can be misleading in imbalanced datasets. For example, if 95% of the data belongs to one class, a model that always predicts the majority class will have 95% accuracy but will fail to identify the minority class.

3. **Poor Generalization**:

 - Models trained on imbalanced data may not generalize well to new, unseen data, especially if the minority class is underrepresented.


Some methods to handle imbalanced datasets:
1. **Resampling Methods**:

 - Oversampling: Increase the number of instances in the minority class by duplicating or generating synthetic samples (e.g., SMOTE).
 - Undersampling: Reduce the number of instances in the majority class to balance the dataset.

2. **Evaluation Metrics**:

 - Use appropriate evaluation metrics such as precision, recall, F1-score, ROC-AUC, and confusion matrix instead of accuracy to better assess model performance on imbalanced data.

3. **Algorithmic Approaches**:

 - Use algorithms that are designed to handle imbalanced data, such as decision trees, random forests, or ensemble methods.
 - Adjust class weights in algorithms to give more importance to the minority class.

In [694]:
# Write your code here

# 3. Compile Preprocessing Pipeline

All of the preprocessing classes or functions defined earlier will be compiled in this step.

If you use sklearn to create preprocessing classes, you can list your preprocessing classes in the Pipeline object sequentially, and then fit and transform your data.

In [697]:
# # Note: You can add or delete preprocessing components from this pipeline
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='mean'))  # Replace NaN with mean values
    ])

# pipe = Pipeline([("imputer", FeatureImputer()),
#                  ("featurecreator", FeatureCreator()),
#                  ("scaler", FeatureScaler()),
#                  ("encoder", FeatureEncoder())])

# train_set = pipe.fit_transform(train_set)
# val_set = pipe.transform(val_set)

In [698]:
# # Your code should work up until this point
# train_set = pipe.fit_transform(train_set)
# val_set = pipe.transform(val_set)

or create your own here

In [700]:
# Write your code here

# 4. Modeling and Validation

Modelling is the process of building your own machine learning models to solve specific problems, or in this assignment context, predicting the target feature `label`. Validation is the process of evaluating your trained model using the validation set or cross-validation method and providing some metrics that can help you decide what to do in the next iteration of development.

## A. KNN

In [703]:
# Type your code here

## B. Naive Bayes

In [705]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import MinMaxScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

def evaluate_model(pipeline, X, y, fold_indices, model_name="Model"):
    """
    Evaluate a model using k-fold cross validation
    """
    fold_scores = []
    fold_reports = []
    
    for fold_num, (train_idx, val_idx) in enumerate(fold_indices, 1):
        # Split data for this fold
        X_train_fold = X.iloc[train_idx]
        y_train_fold = y.iloc[train_idx]
        X_val_fold = X.iloc[val_idx]
        y_val_fold = y.iloc[val_idx]
        
        # Fit and predict
        pipeline.fit(X_train_fold, y_train_fold)
        y_pred = pipeline.predict(X_val_fold)
        
        # Calculate metrics
        accuracy = accuracy_score(y_val_fold, y_pred)
        report = classification_report(y_val_fold, y_pred)
        
        fold_scores.append(accuracy)
        fold_reports.append(report)
        
        print(f"\n{model_name} - Fold {fold_num} Results:")
        print(f"Accuracy: {accuracy:.4f}")
        print("\nClassification Report:")
        print(report)
    
    # Print average results
    mean_accuracy = np.mean(fold_scores)
    std_accuracy = np.std(fold_scores)
    print(f"\n{model_name} - Overall Results:")
    print(f"Average Accuracy: {mean_accuracy:.4f} (+/- {std_accuracy:.4f})")
    
    return fold_scores, fold_reports

def gaussian_nb(df, fold_indices):
    features = [
        'DegitRatioInURL',
        'SpacialCharRatioInURL',
        'CharContinuationRate',
        'NoOfOtherSpecialCharsInURL',
        'URLCharProb',
        'DomainTitleMatchScore',
        'URLTitleMatchScore'
    ]
    
    # Select features and target
    X = df[features]
    y = df['label']
    
    # Create pipeline
    pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='mean')),
        ('classifier', GaussianNB())
    ])
    
    return evaluate_model(pipeline, X, y, fold_indices, "Gaussian NB")

def multinomial_nb(df, fold_indices):
    count_features = [
        'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef', 
        'NoOfExternalRef', 'NoOfSubDomain', 'NoOfObfuscatedChar', 'NoOfLettersInURL',
        'NoOfDegitsInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL',
        'NoOfOtherSpecialCharsInURL'
    ]
    
    # Select features and target
    X = df[count_features]
    y = df['label']
    
    # Create pipeline
    pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value=0)),
        ('scaler', MinMaxScaler()),
        ('classifier', MultinomialNB())
    ])
    
    return evaluate_model(pipeline, X, y, fold_indices, "Multinomial NB")

def complement_nb(df, fold_indices):
    count_features = [
        'IsDomainIP',
        'HasObfuscation',
        'IsHTTPS',        
        'HasTitle',       
        'HasFavicon',     
        'Robots',         
        'IsResponsive',   
        'HasDescription',
        'HasExternalFormSubmit',
        'HasSocialNet',   
        'HasSubmitButton',
        'HasHiddenFields',
        'HasPasswordField',
        'Bank',
        'Crypto',
        'Pay',
        'HasCopyRightInfo'
    ]
    
    # Select features and target
    X = df[count_features]
    y = df['label']
    
    # Create pipeline
    pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value=0)),
        ('scaler', MinMaxScaler()),
        ('classifier', ComplementNB())
    ])
    
    return evaluate_model(pipeline, X, y, fold_indices, "Complement NB")

def bernoulli_nb(df, fold_indices):
    binary_features = [
        'IsDomainIP',
        'HasObfuscation',
        'IsHTTPS',        
        'HasTitle',       
        'HasFavicon',     
        'Robots',         
        'IsResponsive',   
        'HasDescription',
        'HasExternalFormSubmit',
        'HasSocialNet',   
        'HasSubmitButton',
        'HasHiddenFields',
        'HasPasswordField',
        'Bank',
        'Crypto',
        'Pay',
        'HasCopyRightInfo',
    ]
    
    # Select features and target
    X = df[binary_features]
    y = df['label']
    
    # Create pipeline
    pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value=0)),
        ('classifier', BernoulliNB())
    ])
    
    return evaluate_model(pipeline, X, y, fold_indices, "Bernoulli NB")

def categorical_nb(df, fold_indices):
    string_features = ['TLD']
    binary_features = [
        'IsDomainIP',
        'HasObfuscation',
        'IsHTTPS',        
        'HasTitle',       
        'HasFavicon',     
        'Robots',         
        'IsResponsive',   
        'HasDescription',
        'HasExternalFormSubmit',
        'HasSocialNet',   
        'HasSubmitButton',
        'HasHiddenFields',
        'HasPasswordField',
        'Bank',
        'Crypto',
        'Pay',
        'HasCopyRightInfo',
    ]
    
    # Process TLD column
    df = df.copy()
    df['TLD'] = df['TLD'].astype(str)
    
    # Select features and target
    X = df[string_features + binary_features]
    y = df['label']
    
    # Create preprocessing steps
    categorical_transformer = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
        ('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=498))
    ])
    
    binary_transformer = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value=0))
    ])
    
    # Combine transformers
    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', categorical_transformer, string_features),
            ('bin', binary_transformer, binary_features)
        ])
    
    # Create pipeline
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', CategoricalNB(min_categories=499))
    ])
    
    return evaluate_model(pipeline, X, y, fold_indices, "Categorical NB")

In [706]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

# Assuming df is your dataset
# Create fold indices
fold_indices = prepare_kfold_split(df, 100)

# Run all models and collect results
results = {}

# Gaussian NB
print("\nRunning Gaussian Naive Bayes...")
gaussian_scores, gaussian_reports = gaussian_nb(df, fold_indices)
results['Gaussian NB'] = gaussian_scores

# Multinomial NB
print("\nRunning Multinomial Naive Bayes...")
multinomial_scores, multinomial_reports = multinomial_nb(df, fold_indices)
results['Multinomial NB'] = multinomial_scores

# Complement NB
print("\nRunning Complement Naive Bayes...")
complement_scores, complement_reports = complement_nb(df, fold_indices)
results['Complement NB'] = complement_scores

# Bernoulli NB
print("\nRunning Bernoulli Naive Bayes...")
bernoulli_scores, bernoulli_reports = bernoulli_nb(df, fold_indices)
results['Bernoulli NB'] = bernoulli_scores

# Categorical NB
print("\nRunning Categorical Naive Bayes...")
categorical_scores, categorical_reports = categorical_nb(df, fold_indices)
results['Categorical NB'] = categorical_scores

# Create summary statistics
summary_stats = {
    'Model': [],
    'Mean Accuracy': [],
    'Std Accuracy': [],
    'Min Accuracy': [],
    'Max Accuracy': []
}

for model_name, scores in results.items():
    summary_stats['Model'].append(model_name)
    summary_stats['Mean Accuracy'].append(np.mean(scores))
    summary_stats['Std Accuracy'].append(np.std(scores))
    summary_stats['Min Accuracy'].append(np.min(scores))
    summary_stats['Max Accuracy'].append(np.max(scores))

summary_df = pd.DataFrame(summary_stats)
summary_df = summary_df.sort_values('Mean Accuracy', ascending=False)

# Print summary table
print("\nModel Performance Summary:")
print("=========================")
print(summary_df.to_string(index=False))

# Create visualizations
plt.figure(figsize=(12, 6))

# Box plot
plt.subplot(1, 2, 1)
data_to_plot = [scores for scores in results.values()]
plt.boxplot(data_to_plot, labels=results.keys())
plt.title('Model Performance Distribution')
plt.xticks(rotation=45)
plt.ylabel('Accuracy')

# Bar plot with error bars
plt.subplot(1, 2, 2)
models = list(results.keys())
means = [np.mean(scores) for scores in results.values()]
stds = [np.std(scores) for scores in results.values()]

x_pos = np.arange(len(models))
plt.bar(x_pos, means, yerr=stds, align='center', alpha=0.8, 
        capsize=5, color='skyblue', ecolor='black')
plt.xticks(x_pos, models, rotation=45)
plt.title('Average Model Performance')
plt.ylabel('Accuracy')

plt.tight_layout()
plt.show()

# Create heatmap of model correlations
correlations = pd.DataFrame(index=models, columns=models)
for i, model1 in enumerate(models):
    for j, model2 in enumerate(models):
        corr = np.corrcoef(results[model1], results[model2])[0,1]
        correlations.loc[model1, model2] = corr

plt.figure(figsize=(10, 8))
sns.heatmap(correlations, annot=True, cmap='RdBu', center=0, vmin=-1, vmax=1)
plt.title('Model Prediction Correlation Matrix')
plt.tight_layout()
plt.show()

# Print detailed analysis for best model
best_model = summary_df.iloc[0]['Model']
best_scores = results[best_model]
best_reports = globals()[f"{best_model.lower().replace(' ', '_')}_reports"]

print(f"\nDetailed Analysis of Best Model ({best_model}):")
print("============================================")
print(f"Average Accuracy: {np.mean(best_scores):.4f} (+/- {np.std(best_scores):.4f})")
print("\nDetailed performance by fold:")
for fold, (score, report) in enumerate(zip(best_scores, best_reports), 1):
    print(f"\nFold {fold}:")
    print(f"Accuracy: {score:.4f}")
    print("Classification Report:")
    print(report)

Fold 1:
Training samples: 138999
Validation samples: 1405

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 2:
Training samples: 138999
Validation samples: 1405

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 3:
Training samples: 138999
Validation samples: 1405

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 4:
Training samples: 138999
Validation samples: 1405

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 5:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 6:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 7:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 8:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 9:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 10:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 11:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 12:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 13:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 14:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 15:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 16:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 17:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 18:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 19:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 20:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 21:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 22:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 23:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 24:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 25:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 26:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 27:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 28:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 29:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 30:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 31:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 32:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 33:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 34:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 35:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 36:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 37:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 38:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 39:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 40:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 41:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 42:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 43:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 44:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 45:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 46:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 47:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 48:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 49:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 50:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 51:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 52:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 53:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 54:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 55:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 56:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 57:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 58:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 59:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 60:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 61:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 62:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 63:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 64:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 65:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 66:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 67:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 68:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 69:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 70:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 71:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 72:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 73:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 74:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 75:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 76:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 77:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 78:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 79:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 80:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 81:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Fold 82:
Training samples: 139000
Validation samples: 1404

Training label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64

Validation label distribution:
label
1    0.925
0    0.075
Name: proportion, dtype: float64


C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Multinomial NB - Fold 14 Results:
Accuracy: 0.9252

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.46      0.50      0.48      1404
weighted avg       0.86      0.93      0.89      1404


Multinomial NB - Fold 15 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 16 Results:
Accuracy: 0.9309

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.08      0.14       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.97      0.54      0.55      1404
weighted avg       0.94      0.93      0.90      1404


Multinomial NB - Fold 17 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 18 Results:
Accuracy: 0.9295

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.06      0.11       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.53      0.54      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 19 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 20 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 21 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 22 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 23 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 24 Results:
Accuracy: 0.9295

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.06      0.11       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.53      0.54      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 25 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 26 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 27 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 28 Results:
Accuracy: 0.9288

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.05      0.09       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.53      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 29 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 30 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 31 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 32 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 33 Results:
Accuracy: 0.9288

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.05      0.09       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.53      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 34 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 35 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 36 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 37 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 38 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 39 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 40 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 41 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 42 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 43 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 44 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 45 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 46 Results:
Accuracy: 0.9323

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.10      0.17       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.97      0.55      0.57      1404
weighted avg       0.94      0.93      0.91      1404


Multinomial NB - Fold 47 Results:
Accuracy: 0.9288

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.05      0.09       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.53      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 48 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 49 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 50 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       105
           1       0.93      1.00      0.96      1299

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 51 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 52 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 53 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 54 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 55 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 56 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 57 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 58 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 59 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.05      0.09       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.53      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 60 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 61 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 62 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 63 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298


C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Multinomial NB - Fold 64 Results:
Accuracy: 0.9245

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       106
           1       0.92      1.00      0.96      1298

    accuracy                           0.92      1404
   macro avg       0.46      0.50      0.48      1404
weighted avg       0.85      0.92      0.89      1404


Multinomial NB - Fold 65 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 66 Results:
Accuracy: 0.9252

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 67 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 68 Results:
Accuracy: 0.9252

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 69 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 70 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 71 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 72 Results:
Accuracy: 0.9252

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 73 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 74 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 75 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 76 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 77 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 78 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 79 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 80 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 81 Results:
Accuracy: 0.9288

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.06      0.11       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.53      0.54      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 82 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 83 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404

C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Multinomial NB - Fold 84 Results:
Accuracy: 0.9245

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       106
           1       0.92      1.00      0.96      1298

    accuracy                           0.92      1404
   macro avg       0.46      0.50      0.48      1404
weighted avg       0.85      0.92      0.89      1404


Multinomial NB - Fold 85 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 86 Results:
Accuracy: 0.9281

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.05      0.09       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.53      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 87 Results:
Accuracy: 0.9252

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 88 Results:
Accuracy: 0.9266

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.51      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 89 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 90 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 91 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 92 Results:
Accuracy: 0.9295

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.07      0.12       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.53      0.54      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 93 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 94 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 95 Results:
Accuracy: 0.9288

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.06      0.11       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.53      0.54      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 96 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404


Multinomial NB - Fold 97 Results:
Accuracy: 0.9259

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.02      0.04       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.51      0.50      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Fold 98 Results:
Accuracy: 0.9274

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.04      0.07       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.52      0.52      1404
weighted avg       0.93      0.93      0.90      1404

C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\David\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Multinomial NB - Fold 99 Results:
Accuracy: 0.9245

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       106
           1       0.92      1.00      0.96      1298

    accuracy                           0.92      1404
   macro avg       0.46      0.50      0.48      1404
weighted avg       0.85      0.92      0.89      1404


Multinomial NB - Fold 100 Results:
Accuracy: 0.9252

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.01      0.02       106
           1       0.93      1.00      0.96      1298

    accuracy                           0.93      1404
   macro avg       0.96      0.50      0.49      1404
weighted avg       0.93      0.93      0.89      1404


Multinomial NB - Overall Results:
Average Accuracy: 0.9271 (+/- 0.0014)

Running Complement Naive Bayes...

KeyError: "['HasCopyRightInfo'] not in index"

In [ ]:
def bernoulli_nb_scratch(df):
    binary_features = [
        'IsDomainIP','HasObfuscation','IsHTTPS','HasTitle','HasFavicon',     
        'Robots','IsResponsive','HasDescription','HasExternalFormSubmit','HasSocialNet',   
        'HasSubmitButton','HasHiddenFields','HasPasswordField','Bank','Crypto','Pay',
        'HasCopyRightInfo',
    ]
    
    # Select features and target
    X = df[binary_features]
    y = df['label']
    
    # Create pipeline
    pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value=0)),
        ('classifier', BernoulliNB())
    ])

import numpy as np
from collections import defaultdict

def train_bernoulli_nb(X, y, alpha=1.0):
    # Convert inputs to numpy arrays
    X = np.asarray(X)
    y = np.asarray(y)
    
    # Get unique classes and number of features
    classes = np.unique(y)
    n_samples, n_features = X.shape
    
    # Calculate class prior probabilities
    class_priors = {}
    for c in classes:
        n_c = np.sum(y == c)  # Count documents in class
        class_priors[c] = n_c / n_samples
    
    # Calculate conditional probabilities for each feature
    feature_probs = defaultdict(dict)
    for c in classes:
        # Get documents belonging to current class
        x_c = X[y == c]
        n_c = len(x_c)
        
        # Calculate probability for each feature with Laplace smoothing
        for feature_idx in range(n_features):
            n_tc = np.sum(x_c[:, feature_idx])  # Count documents with feature
            prob = (n_tc + alpha) / (n_c + 2 * alpha)
            feature_probs[c][feature_idx] = prob
    
    return {
        'classes': classes,
        'class_priors': class_priors,
        'feature_probs': feature_probs
    }

def predict_bernoulli_nb(X, model):
    X = np.asarray(X)
    predictions = []
    
    for x in X:
        # Calculate score for each class
        scores = {}
        for c in model['classes']:
            # Start with log of class prior
            score = np.log(model['class_priors'][c])
            
            # Add log probabilities for each feature
            for feature_idx, feature_val in enumerate(x):
                prob = model['feature_probs'][c][feature_idx]
                if feature_val == 1:
                    score += np.log(prob)
                else:
                    score += np.log(1 - prob)
            
            scores[c] = score
        
        # Predict class with highest score
        predicted_class = max(scores, key=scores.get)
        predictions.append(predicted_class)
    
    return np.array(predictions)

def evaluate_model(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    
    accuracy = np.mean(y_true == y_pred)
    
    # Calculate per-class metrics
    classes = np.unique(y_true)
    per_class_metrics = {}
    
    for c in classes:
        true_c = y_true == c
        pred_c = y_pred == c
        
        tp = np.sum(true_c & pred_c)
        fp = np.sum(~true_c & pred_c)
        fn = np.sum(true_c & ~pred_c)
        
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
        
        per_class_metrics[c] = {
            'precision': precision,
            'recall': recall,
            'f1_score': f1
        }
    
    return {
        'accuracy': accuracy,
        'per_class_metrics': per_class_metrics
    }

## C. Improvements (Optional)

- **Visualize the model evaluation result**

This will help you to understand the details more clearly about your model's performance. From the visualization, you can see clearly if your model is leaning towards a class than the others. (Hint: confusion matrix, ROC-AUC curve, etc.)

- **Explore the hyperparameters of your models**

Each models have their own hyperparameters. And each of the hyperparameter have different effects on the model behaviour. You can optimize the model performance by finding the good set of hyperparameters through a process called **hyperparameter tuning**. (Hint: Grid search, random search, bayesian optimization)

- **Cross-validation**

Cross-validation is a critical technique in machine learning and data science for evaluating and validating the performance of predictive models. It provides a more **robust** and **reliable** evaluation method compared to a hold-out (single train-test set) validation. Though, it requires more time and computing power because of how cross-validation works. (Hint: k-fold cross-validation, stratified k-fold cross-validation, etc.)

In [ ]:
# Type your code here

## D. Submission
To predict the test set target feature and submit the results to the kaggle competition platform, do the following:
1. Create a new pipeline instance identical to the first in Data Preprocessing
2. With the pipeline, apply `fit_transform` to the original training set before splitting, then only apply `transform` to the test set.
3. Retrain the model on the preprocessed training set
4. Predict the test set
5. Make sure the submission contains the `id` and `label` column.

Note: Adjust step 1 and 2 to your implementation of the preprocessing step if you don't use pipeline API from `sklearn`.

In [ ]:
# Type your code here

# 6. Error Analysis

Based on all the process you have done until the modeling and evaluation step, write an analysis to support each steps you have taken to solve this problem. Write the analysis using the markdown block. Some questions that may help you in writing the analysis:

- Does my model perform better in predicting one class than the other? If so, why is that?
- To each models I have tried, which performs the best and what could be the reason?
- Is it better for me to impute or drop the missing data? Why?
- Does feature scaling help improve my model performance?
- etc...

`Provide your analysis here`